name: ðŸž Bug report
description: Create a bug report to help us improve NativeScript
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        > ## Important :rotating_light::
        > 
        > The issue list is reserved exclusively for bug reports and feature requests. That means we do not accept usage questions. If you open an issue that does not conform to the requirements, it will be closed.

        For usage questions, please refer to the following resources:
        * Search the [docs](https://docs.nativescript.org/)
        * Search or ask on [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript)
        * Search or ask in [Discussions](https://github.com/NativeScript/NativeScript/discussions)
        * Watch [video tutorials](https://nativescripting.com/)

        Before you continue filling out this form, please confirm the following:

        **1. Is there an existing issue for this?**

        Please search to see if an issue already exists for the bug you encountered or is not already reported in [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) as a question.

        **2. Confirm you are submitting a bug report**

        Please confirm you are submitting a bug report and not a usage question.

        **3. Code of Conduct**

        By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

        ---
  - type: checkboxes
    attributes:
      options:
        - label: I have searched the existing issues as well as StackOverflow and this has not been posted before
          required: true
        - label: Yes, this is a bug report
          required: true
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: textarea
    attributes:
      label: Current Behavior
      description: |
        A clear and concise description of what the bug is. 
        Please, explain whether it's a build time error or a runtime error.
      placeholder: |
        When I do <X>, <Y> happens and I see the following error message:

        ```
        <error message>
        ```
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
      placeholder: |
        When I do <X>, <Z> should happen instead.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Steps To Reproduce and additional context
      description: |
        Add commands used or steps taken to reproduce the behaviour.
        Include links, references or anything else that will give us more context about the issue you are encountering.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: false

  - type: textarea
    attributes:
      label: Relevant log output (if applicable)
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    attributes:
      label: Environment
      description: |
        Provide information about your environment.
        Run ns info inside the project and paste the output directly without manual formatting:
    validations:
      required: false
