name: Bug Report
description: File a bug report
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! If you have usage questions, please use [Discussions](#).
  - type: checkboxes
    id: terms_issues
    attributes:
      label: Confirm you are submitting a bug report.
      description: Please confirm you are submitting a bug report and not a usage question. For usage questions, please use [Discussions](#).
      options:
        - label: Yes, this is a bug report.
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 8.x (Default)
        - 7.x
        - 6.x
        - Older
    validations:
      required: true
  - type: dropdown
    id: platforms
    attributes:
      label: What platforms are you seeing the problem on?
      multiple: true
      options:
        - Android
        - iOS
  - type: dropdown
    id: host-platform
    attributes:
      label: What platform are you developing on?
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
