name: 🐞 Bug report
description: Create a bug report to help us improve NativeScript
labels: [bug]
body:
- type: markdown
  attributes:
    value: |
      **:rotating_light: The issue list is reserved exclusively for bug reports and feature requests. That means we do not accept usage questions. If you open an issue that does not conform to the requirements, it will be closed.**

      For usage questions, please refer to the following resources:
      * Search the [docs](https://docs.nativescript.org/)
      * Search or ask on [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript)
      * Search or ask in [Discussions](https://github.com/NativeScript/NativeScript/discussions)
      * Watch [video tutorials](https://nativescripting.com/)

      Before you continue filling out this form, please confirm the following:

      **Is there an existing issue for this?**

      Please search to see if an issue already exists for the bug you encountered or is not already reported in StackOverflow as a question...

      **Confirm you are submitting a bug report**

      Please confirm you are submitting a bug report and not a usage question.

      ---
- type: checkboxes
  attributes:
    options:
    - label: I have searched the existing issues as well as StackOverflow and this has not been posted before
      required: true
    - label: Yes, this is a bug report
      required: true

- type: textarea
  attributes:
    label: Current Behavior
    description: |
      A clear and concise description of what the bug is. 
      Please, explain whether it's a build time error or a runtime error. 
    placeholder: |
      When I do <X>, <Y> happens and I see the error message attached below:
      ```
      ...
      ```
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
    placeholder: When I do <X>, <Z> should happen instead.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Add commands used or steps taken to reproduce the behaviour.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      Provide version numbers for the following components (information can be retrieved by running `ns info` in your project folder or by inspecting the `package.json` of the project):
    value: |
      - CLI Version (ns -v): 
      - Core Version (@nativescript/core - 8.x, 7.x, 6.x etc.): 
      - Android Runtime (@nativescript/android): 
      - iOS Runtime (@nativescript/ios): 
      - XCode Version (xcodebuild -version): 
      - Plugin(s) (dependencies and devDependencies in package.json): 
    render: markdown
  validations:
    required: false
- type: textarea
  id: logs
  attributes:
    label: Relevant log output
    description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    render: shell
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
  validations:
    required: false
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
    options:
    - label: I agree to follow this project's Code of Conduct
  validations:
    required: true